
# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$hostname\
$localip\
$kubernetes\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$docker_context\
$package\
$bun\
$c\
$cmake\
$dart\
$elm\
$golang\
$haskell\
$helm\
$java\
$gradle\
$lua\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$python\
$ruby\
$rust\
$solidity\
$swift\
$terraform\
$typst\
$vlang\
$vagrant\
$zig\
$buf\
$nix_shell\
$memory_usage\
$aws\
$nats\
$direnv\
$env_var\
$custom\
$sudo\
$cmd_duration\
$line_break\
$jobs\
$battery\
$time\
$status\
$os\
$container\
$shell\
$character"""

# Inserts a blank line between shell prompts
add_newline = true

# Replace the '❯' symbol in the prompt with '$'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[\$](bold #FF8C00)'

[directory]
style = 'bold green'

[hostname]
ssh_only = false
disabled = false
style = 'bold cyan'

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[username]
disabled = false
show_always = true
style_user = 'bold blue'
format = '[$user]($style) at '
