theme = "onedark"

[editor]
line-number = "relative"
auto-completion = false

[editor.cursor-shape]
insert = "bar"

# [editor.inline-diagnostics]
# cursor-line = "warning"
# other-lines = "warning"

[editor.lsp]
display-signature-help-docs = false
auto-signature-help = false

[keys.insert]
C-b = "move_char_left"
C-f = "move_char_right"
C-s = ":w"
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
pageup = "no_op"
pagedown = "no_op"
home = "no_op"
end = "no_op"

[keys.normal]
a = ["append_mode", "collapse_selection"]
V = ["goto_first_nonwhitespace", "extend_to_line_end"]
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
pageup = "no_op"
pagedown = "no_op"
home = "no_op"
end = "no_op"

[keys.select]
";" = ["collapse_selection", "normal_mode"]

