"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[user]
name = "xxxxxxxx"
email = "xxxxxxxxxxxxxxxxxxx"

[signing]
behavior = "own"
backend = "gpg"
key = "xxxxxxxxxxxxxxxxxxxx"

[ui]
bookmark-list-sort-keys = ["committer-date", "name"]
# Use Difftastic by default
diff-formatter = ["difft", "--color=always", "$left", "$right"]
# Disable all pagination for commands that support it
paginate = "never"
# Use `meld` as diff editor
diff-editor = "meld"
# Use helix as editor
editor = "hx"
# Use `meld` as merge editor
merge-editor = [
  "meld",
  "$left",
  "$base",
  "$right",
  "-o",
  "$output",
  "--auto-merge",
]

[git]
auto-local-bookmark = true

[templates]
commit_trailers = '''format_signed_off_by_trailer(self)'''
